spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://d9city.net:8309/vue-demo?characterEncoding=utf-8&useSSL=false
    username: root
    password: jimy3k0519
server:
  port: 8081

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 设置Mybatis-plus 全局配置
  global-config:
    db-config:
      table-prefix: t_        #设置实体类对应表名的统一前缀：t_
    # 配置类型别名所对应的包  mapper中 *Mapper.xml 使用类型别名，会用到。
  type-aliases-package: com.nicole.vueserver.entity